apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: bookstore-trigger-template
  namespace: sgaikwad
spec:
  params:
  - name: git-revision
    description: The git revision (commit SHA)
  - name: git-url
    description: The git repository URL
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: bookstore-pipeline-run-
      namespace: sgaikwad
    spec:
      serviceAccountName: pipeline-service-account
      pipelineRef:
        name: bookstore-ci-pipeline
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: image-name
        value: quay.io/sureshgaikwad/app
      - name: image-tag
        value: $(tt.params.git-revision)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
      - name: dockerconfig-secret
        secret:
          secretName: quay-auth-secret
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bookstore-trigger-binding
  namespace: sgaikwad
spec:
  params:
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-url
    value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bookstore-event-listener
  namespace: sgaikwad
spec:
  serviceAccountName: pipeline-service-account
  triggers:
  - name: github-trigger
    bindings:
    - ref: bookstore-trigger-binding
    template:
      ref: bookstore-trigger-template
    interceptors:
    - ref:
        name: github
      params:
      - name: secretRef
        value:
          secretName: github-webhook-secret
          secretKey: webhook-secret
      - name: eventTypes
        value:
        - push
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bookstore-webhook-route
  namespace: sgaikwad
spec:
  to:
    kind: Service
    name: el-bookstore-event-listener
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
