apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secret
  namespace: sgaikwad
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: sureshgaikwad
  password: "PASTE TOKEN HERE"  # Replace with your GitHub Personal Access Token
---
# Service account needs to reference the secret
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: sgaikwad
secrets:
- name: quay-secret
- name: github-auth-secret
imagePullSecrets:
- name: quay-secret
