apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-app
  namespace: openshift-gitops
  labels:
    app: bookstore-app
spec:
  project: default
  source:
    repoURL: https://github.com/sureshgaikwad/gitops-catalog
    targetRevision: HEAD
    path: application/book-app
  destination:
    server: https://kubernetes.default.svc
    namespace: sgaikwad
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
